# Generated by Django 3.1.6 on 2022-11-21 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Part', models.TextField(max_length=100)),
                ('Cat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Model2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_name', models.TextField()),
                ('Price', models.CharField(max_length=100)),
                ('Catnumb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.model1')),
            ],
        ),
    ]
